version: 1

models:
  - name: stg_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null

  - name: stg_company
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

  - name: stg_event
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      
