version: 2

models:
  - name: stg_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: company_id
        tests:
          - unique
          - not_null

  - name: stg_company
    columns:
      - name: company_id
        tests:
          - unique
          - not_null

  - name: stg_event
    columns:
      - name: user_id
        tests:
          - not_null
      - name: event_name
        tests:
          - accepted_values:
              values: ['space_create', 'company_create', 'edit_page_create', 'collection_create', 'space_install_gitsyn']
